{
  // 从 Hamster 当前生效的 chinese 键盘手势迁移。
  swipe_up: {
    comma: { action: { character: '.' }, label: { text: '.' } },
    q: { action: { character: '1' }, label: { text: '1' } },
    w: { action: { character: '2' }, label: { text: '2' } },
    e: { action: { character: '3' }, label: { text: '3' } },
    r: { action: { character: '4' }, label: { text: '4' } },
    t: { action: { character: '5' }, label: { text: '5' } },
    y: { action: { character: '6' }, label: { text: '6' } },
    u: { action: { character: '7' }, label: { text: '7' } },
    i: { action: { character: '8' }, label: { text: '8' } },
    o: { action: { character: '9' }, label: { text: '9' } },
    p: { action: { character: '0' }, label: { text: '0' } },
    a: { action: { character: '-' }, label: { text: '-' } },
    s: { action: { character: '/' }, label: { text: '/' } },
    d: { action: { character: ':' }, label: { text: ':' } },
    f: { action: { character: ';' }, label: { text: ';' } },
    g: { action: { character: '(' }, label: { text: '(' } },
    h: { action: { character: ')' }, label: { text: ')' } },
    j: { action: { character: '@' }, label: { text: '@' } },
    k: { action: { character: '"' }, label: { text: '"' } },
    l: { action: { character: '\'' }, label: { text: '\'' } },
    z: { action: { character: '_' }, label: { text: '_' } },
    x: { action: { character: '.' }, label: { text: '.' } },
    c: { action: { character: ',' }, label: { text: ',' } },
    v: { action: { character: '|' }, label: { text: '|' } },
    b: { action: { character: '?' }, label: { text: '?' } },
    n: { action: { character: '!' }, label: { text: '!' } },
    m: { action: { character: '`' }, label: { text: '`' } },
    space: { action: { shortcutCommand: '#次选上屏' } },
    enter: { action: { shortcutCommand: '#换行' } },
    backspace: { action: { shortcutCommand: '#重输' } },
    // 不在数字键上绑定“上个输入方案”，避免误切回雾凇全拼。
  },
  swipe_down: {},
  cn9_swipe_up: {},
  cn9_swipe_down: {},
  number_swipe_up: {},
  number_swipe_down: {},
}
